# Generated by Django 4.0.6 on 2022-07-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='thumb_nail',
            field=models.ImageField(blank=True, null=True, upload_to='todo/'),
        ),
    ]
